spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    
  mvc:
    date-format: dd/MM/yyyy
  
  mail:
    host: smtp.gmail.com
    username: developer@redspark.io
    password: 5byNQQ>y
    properties:
      mail.smtp:
        auth: true
        ssl.enable:  true
        starttls.enable: false
        socketFactory.port: 465
        socketFactory.class: javax.net.ssl.SSLSocketFactory
        socketFactory.fallback: false